Models/ErrorViewModel.cs
namespace UniversidadWeb.Models
{
	public class ErrorViewModel
	{
		public string? RequestId { get; set; }

		public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
	}
}

Controllers/AsignaturasController.cs
using Microsoft.AspNetCore.Mvc;
using Entity.Models;
using UniversidadWeb;

namespace Indra.Web.Controllers
{
	public class AsignaturasController : Controller
	{
		private readonly IConfiguration _configuration;
        private readonly string Baseurl;

		public AsignaturasController(IConfiguration configuration)
		{
			_configuration = configuration;
			this.Baseurl = configuration["UrlBase"];
		}

		public async Task<ViewResult> Index()
		{
			Client client = new(Baseurl);
			List<Asignatura> estudiantes = await client.GetList<Asignatura>("api/Asignatura/GetAll");
            IQueryable<Asignatura> query = estudiantes.AsQueryable();
			return View(query.ToList());
		}

		public ActionResult Create()
		{
		    return View();
		}


		[HttpPost]
		public async Task<ActionResult> Create(Asignatura estudiante)
		{
			if (!ModelState.IsValid)
				return ValidationProblem(ModelState);

			var client = new Client(Baseurl);
			var rpta = await client.Post("api/Asignatura", estudiante);
			if (rpta.Codigo == 1)
			{
				return RedirectToAction("Index");
			}
			ModelState.AddModelError(string.Empty, rpta.Mensaje);
			return View(estudiante);
		}

		public async Task<ActionResult> Edit(int id)
		{
            var asignatura = await new Client(Baseurl).GetEntity<Asignatura>($"api/Asignatura/GetById?Id={id}");
            return View(asignatura);
		}

		[HttpPost]
		public async Task<ActionResult> Edit(Asignatura asignatura)
		{
			if (!ModelState.IsValid)
				return View(asignatura);

			var client = new Client(Baseurl);
			var rpta = await client.Put("api/Asignatura", asignatura);
			if (rpta.Codigo == 1)
            {
                return RedirectToAction("Index");
            }
            ModelState.AddModelError(string.Empty, rpta.Mensaje);
            return View(asignatura);
        }
	}
}

Controllers/CalificacionesController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Entity.Models;
using UniversidadWeb;

namespace Indra.Web.Controllers
{
	public class CalificacionesController : Controller
	{
        private readonly IConfiguration _configuration;

        public CalificacionesController(IConfiguration configuration)
        {
            _configuration = configuration;
        }

		private async Task CreateSelectLists()
		{
			ViewBag.Asignaturas = await GetAsignaturas();
			ViewBag.Estudiantes = await GetEstudiantes();
		}

        public async Task<ViewResult> Index()
		{
			List<Calificacion> calificaciones = await new Client(_configuration["UrlBase"]).GetList<Calificacion>("api/Calificacion/GetAll");
            IQueryable<Calificacion> query = calificaciones.AsQueryable();
			query = query.OrderBy(x => x.Id);
			await CreateSelectLists();
			return View(query.ToList());
		}

		public async Task<ActionResult> Create()
		{
			await CreateSelectLists();
		    return View();
		} 
				
		[HttpPost]
		public async Task<ActionResult> Create(Calificacion calificacion)
		{
            if (!ModelState.IsValid)
				return View(calificacion);

			var client = new Client(_configuration["UrlBase"]);
            var rpta = await client.Post("api/Calificacion", calificacion);
			if (rpta.Codigo == 1)
            {
                return RedirectToAction("Index");
            }
            ModelState.AddModelError(string.Empty, rpta.Mensaje);
			await CreateSelectLists();
			return View(calificacion);
        }
				
		public async Task<ActionResult> Edit(int id)
		{
            var calificacion = await new Client(_configuration["UrlBase"]).GetEntity<Calificacion>($"api/Calificaciones/{id}");
			await CreateSelectLists();
			return View(calificacion);
		}
				
		[HttpPost]
		public async Task<ActionResult> Edit(Calificacion calificacion)
		{
            if (!ModelState.IsValid)
                return ValidationProblem(ModelState);

            var client = new Client(_configuration["UrlBase"]);
            var rpta = await client.Put("api/Calificacion", calificacion);
			if (rpta.Codigo == 1)
            {
                return RedirectToAction("Index");
            }
            ModelState.AddModelError(string.Empty, "Server Error. Please contact administrator.");
            await CreateSelectLists();
            return View(calificacion);
        }

		public async Task<List<SelectListItem>> GetAsignaturas()
		{
			Client client = new(_configuration["UrlBase"]);
			var asignaturas = await client.GetList<Asignatura>("api/Asignatura/GetAll");
			var items = new List<SelectListItem>();
			foreach (Asignatura asignatura in asignaturas)
			{
				items.Add(new SelectListItem
				{
					Value = asignatura.Id.ToString(),
					Text = asignatura.Nombre
				});
			}
			return items;
		}

		public async Task<List<SelectListItem>> GetEstudiantes()
		{
			Client client = new(_configuration["UrlBase"]);
			var estudiantes = await client.GetList<Estudiante>("api/Estudiante/GetAll");
			var items = new List<SelectListItem>();
			foreach (Estudiante estudiante in estudiantes)
			{
				items.Add(new SelectListItem
				{
					Value = estudiante.Id.ToString(),
					Text = $"{estudiante.Nombres} {estudiante.Apellidos}"
				});
			}
			return items;
		}
	}
}

Controllers/EstudiantesController.cs
using Microsoft.AspNetCore.Mvc;
using Entity.Models;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.AspNetCore.Mvc.Rendering;
using UniversidadWeb;

namespace Indra.Web.Controllers
{
	public class EstudiantesController : Controller
	{
		private readonly IConfiguration _configuration;

		public EstudiantesController(IConfiguration configuration)
		{
			_configuration = configuration;
		}

		public async Task<ViewResult> Index()
		{
			Client client = new(_configuration["UrlBase"]);
			List<Estudiante> estudiantes = await client.GetList<Estudiante>("api/Estudiante/GetAll");
			return View(estudiantes);
		}

		public async Task<ActionResult> Create()
		{
			ViewBag.Generos = await GetGeneros();
			return View();
		}

		[HttpPost]
		public async Task<ActionResult> Create(Estudiante estudiante)
		{
			if (!ModelState.IsValid)
				return ValidationProblem(ModelState);

			var client = new Client(_configuration["UrlBase"]);
			var rpta = await client.Post("api/Estudiante", estudiante);
			if (rpta.Codigo == 1)
			{
				return RedirectToAction("Index");
			}
			ModelState.AddModelError(string.Empty, rpta.Mensaje);
			return View(estudiante);
		}
		
		public async Task<ViewResult> Details(int id)
		{
			var estudiante = await new Client(_configuration["UrlBase"]).GetEntity<Estudiante>($"api/Estudiante/GetById?Id={id}");
            return View(estudiante);
		}

		public async Task<ActionResult> Edit(int id)
		{
            var estudiante = await new Client(_configuration["UrlBase"]).GetEntity<Estudiante>($"api/Estudiante/GetById?Id={id}");
			ViewBag.Generos = await GetGeneros();
            return View(estudiante);
		}

		[HttpPost]
		public async Task<ActionResult> Edit(Estudiante estudiante)
		{
			if (!ModelState.IsValid)
				return ValidationProblem(ModelState);

            var client = new Client(_configuration["UrlBase"]);
			var rpta = await client.Put("api/Estudiante", estudiante);
			if (rpta.Codigo == 1)
            {
                return RedirectToAction("Index");
            }
            ModelState.AddModelError(string.Empty, rpta.Mensaje);
            return View(estudiante);
        }

		public async Task<List<SelectListItem>> GetGeneros()
		{
			Client client = new(_configuration["UrlBase"]);
			var generos = await client.GetList<Genero>("api/Genero/GetAll");
			var items = new List<SelectListItem>();
			foreach (Genero genero in generos)
			{
				items.Add(new SelectListItem
				{
					Value = genero.Id.ToString(),
					Text = genero.Nombre
				});
			}
			return items;
		}
	}
}

Controllers/IndraModelController.cs
using Microsoft.AspNetCore.Mvc;

namespace Indra.Web.Controllers
{
	public class IndraModelController : Controller
	{
		public ActionResult Index()
		{
			return View();
		}
	}
}

Views/Asignaturas/Create.cshtml
@model Entity.Models.Asignatura
@{
	//ViewBag.Title = "Create";
}

@using (Html.BeginForm("Create", "Asignaturas", FormMethod.Post, new { @class = "form-horizontal" })) {
	@Html.ValidationSummary(true)
	<fieldset>

		@Html.Partial("_CreateOrEdit", Model)

		<div class="control-group">
			<div class="controls">
				<input type="submit" value="Guardar" class="btn btn-success" />
				@Html.ActionLink("Cancelar", "Index", null, new { @class = "btn" })
			</div>
		</div>
	</fieldset>
}

Views/Asignaturas/Edit.cshtml
@model Entity.Models.Asignatura
@{
	//ViewBag.Title = "Edit";
}

@using (Html.BeginForm("Edit", "Asignaturas", FormMethod.Post, new { @class = "form-horizontal" })) {
	@Html.ValidationSummary(true)
	<fieldset>
		<legend>Calificacion</legend>

			@Html.HiddenFor(model => model.Id)
			@Html.Partial("_CreateOrEdit", Model)

		<div class="control-group">
			<div class="controls">
				<input type="submit" value="Guardar" class="btn btn-success" />
				@Html.ActionLink("Cancelar", "Index", null, new { @class = "btn" })
			</div>
		</div>
	</fieldset>
}

Views/Asignaturas/Index.cshtml
@using Entity.Models
@model List<Asignatura>

<div class="row">
	<div class="span8">
	</div>
	<div class="span4">
		@Html.ActionLink("Crear", "Create", null, new { @class = "btn btn-primary pull-right" })
	</div>
</div>

<table class="table table-bordered table-striped table-condensed table-hover">
	<thead>
		<tr>
			<th></th>
			<th>
				<small>@Html.DisplayNameFor(model => model[0].Nombre)</small>
			</th>
			<th>
				<small>@Html.DisplayNameFor(model => model[0].Creditos)</small>
			</th>
			<th>
				<small>@Html.DisplayNameFor(model => model[0].Activo)</small>
			</th>
		</tr>
	</thead>
@foreach (var item in (List<Asignatura>)Model) {
	<tr>

		<td>
			<div class="btn-group">
					<a href="@Url.Action("Edit", new { Id = item.Id })" class="btn btn-mini btn-warning"><i class="icon-pencil"></i> Editar</a>
			</div>
		</td>
		<td>
			<small>@item.Nombre</small>
		</td>
		<td>
			<small>@item.Creditos</small>
		</td>
			<td>
				<small>@item.Activo</small>
			</td>
	</tr>
}
</table>

Views/Asignaturas/_CreateOrEdit.cshtml
@model Entity.Models.Asignatura

<div class="control-group">
	@Html.LabelFor(model => model.Nombre, new { @class = "control-label" })
	<div class="controls">
		@Html.EditorFor(model => model.Nombre)
		@Html.ValidationMessageFor(model => model.Nombre)
	</div>
</div>
<div class="control-group">
	@Html.LabelFor(model => model.Creditos, new { @class = "control-label" })
	<div class="controls">
		@Html.EditorFor(model => model.Creditos)
		@Html.ValidationMessageFor(model => model.Creditos)
	</div>
</div>
<div class="control-group">
	@Html.LabelFor(model => model.Activo, new { @class = "control-label" })
	<div class="controls">
		<select asp-for="Activo">
			<option value="true" selected>Activo</option>
			<option value="false">Inactivo</option>
		</select>
		@Html.ValidationMessageFor(model => model.Activo)
	</div>
</div>

Views/Calificaciones/Create.cshtml
@model Entity.Models.Calificacion
@{
	//ViewBag.Title = "Create";
}

@using (Html.BeginForm("Create", "Calificaciones", FormMethod.Post, new { @class = "form-horizontal" })) {
	@Html.ValidationSummary(true)
	<fieldset>

		@Html.Partial("_CreateOrEdit", Model)

		<div class="control-group">
			<div class="controls">
				<input type="submit" value="Guardar" class="btn btn-success" />
				@Html.ActionLink("Cancelar", "Index", null, new { @class = "btn" })
			</div>
		</div>
	</fieldset>
}

Views/Calificaciones/Edit.cshtml
@model Entity.Models.Calificacion
@{
	//ViewBag.Title = "Edit";
}

@using (Html.BeginForm("Edit", "Calificaciones", FormMethod.Post, new { @class = "form-horizontal" })) {
	@Html.ValidationSummary(true)
	<fieldset>
		<legend>Calificacion</legend>

			@Html.HiddenFor(model => model.Id)
			@Html.Partial("_CreateOrEdit", Model)

		<div class="control-group">
			<div class="controls">
				<input type="submit" value="Guardar" class="btn btn-success" />
				@Html.ActionLink("Cancelar", "Index", null, new { @class = "btn" })
			</div>
		</div>
	</fieldset>
}

Views/Calificaciones/Index.cshtml
@using Entity.Models
@model List<Calificacion>

<div class="row">
	<div class="span8">
	</div>
	<div class="span4">
		@Html.ActionLink("Crear", "Create", null, new { @class = "btn btn-primary pull-right" })
	</div>
</div>

<table class="table table-bordered table-striped table-condensed table-hover">
	<thead>
		<tr>
			<th></th>
			<th>
				<small>@Html.DisplayNameFor(model => model[0].IdAsignatura)</small>
			</th>
			<th>
				<small>@Html.DisplayNameFor(model => model[0].Corte)</small>
			</th>
			<th>
				<small>@Html.DisplayNameFor(model => model[0].Nota)</small>
			</th>
			<th>
				<small>Estudiante</small>
			</th>
		</tr>
	</thead>
@foreach (var item in (List<Calificacion>)Model) {
	<tr>

		<td>
			<div class="btn-group">
					<a href="@Url.Action("Edit", new { Id = item.Id })" class="btn btn-mini btn-warning"><i class="icon-pencil"></i> Editar</a>
			</div>
		</td>
		<td>
			<select asp-for="@item.IdAsignatura" asp-items="@((IEnumerable<SelectListItem>)ViewBag.Asignaturas)" class="form-control-plaintext" disabled="disabled">
			</select>
		</td>
		<td>
			<small>@item.Corte</small>
		</td>
		<td>
			<small>@item.Nota</small>
		</td>
		<td>
				<select asp-for="@item.IdEstudiante" asp-items="@((IEnumerable<SelectListItem>)ViewBag.Estudiantes)" class="form-control-plaintext" disabled="disabled">
				</select>
		</td>
	</tr>
}
</table>

Views/Calificaciones/_CreateOrEdit.cshtml
@model Entity.Models.Calificacion

<div class="control-group">
	@Html.LabelFor(model => model.IdAsignatura, new { @class = "control-label" })
	<div class="controls">
		<select asp-for="IdAsignatura" asp-items="@((IEnumerable<SelectListItem>)ViewBag.Asignaturas)" class="">
		</select>
		@Html.ValidationMessageFor(model => model.IdAsignatura)
	</div>
</div>
<div class="control-group">
	@Html.LabelFor(model => model.IdEstudiante, new { @class = "control-label" })
	<div class="controls">
		<select asp-for="IdEstudiante" asp-items="@((IEnumerable<SelectListItem>)ViewBag.Estudiantes)" class="">
		</select>
		@Html.ValidationMessageFor(model => model.IdEstudiante)
	</div>
</div>
<div class="control-group">
	@Html.LabelFor(model => model.Corte, new { @class = "control-label" })
	<div class="controls">
		@Html.EditorFor(model => model.Corte)
		@Html.ValidationMessageFor(model => model.Corte)
	</div>
</div>
<div class="control-group">
	@Html.LabelFor(model => model.Nota, new { @class = "control-label" })
	<div class="controls">
		@Html.EditorFor(model => model.Nota)
		@Html.ValidationMessageFor(model => model.Nota)
	</div>
</div>

Views/Estudiantes/Create.cshtml
@model Entity.Models.Estudiante
@{
	//ViewBag.Title = "Create";
}

@using (Html.BeginForm("Create", "Estudiantes", FormMethod.Post, new { @class = "form-horizontal" })) {
	@Html.ValidationSummary(true)
	<fieldset>

		@Html.Partial("_CreateOrEdit", Model)

		<div class="control-group">
			<div class="controls">
				<input type="submit" value="Guardar" class="btn btn-success" />
				@Html.ActionLink("Cancelar", "Index", null, new { @class = "btn" })
			</div>
		</div>
	</fieldset>
}

Views/Estudiantes/Edit.cshtml
@model Entity.Models.Estudiante
@{
	//ViewBag.Title = "Edit";
}

<ul class="breadcrumb">
	<li><a href="\">Tables</a> <span class="divider">/</span></li>
	<li>@Html.ActionLink("Estudiantes", "Index", "Estudiantes") <span class="divider">/</span></li>
	<li class="active">Edit</li>
</ul>

@using (Html.BeginForm("Edit", "Estudiantes", FormMethod.Post, new { @class = "form-horizontal" })) {
	@Html.ValidationSummary(true)
	<fieldset>
		<legend>Estudiante</legend>

			@Html.HiddenFor(model => model.Id)
			@Html.Partial("_CreateOrEdit", Model)

		<div class="control-group">
			<div class="controls">
				<input type="submit" value="Guardar" class="btn btn-success" />
				@Html.ActionLink("Cancelar", "Index", null, new { @class = "btn" })
			</div>
		</div>
	</fieldset>
}

Views/Estudiantes/Index.cshtml
@using Entity.Models;
@model List<Entity.Models.Estudiante>

<div class="row">
	<div class="span8">
	</div>
	<div class="span4">
		@Html.ActionLink("Crear", "Create", null, new { @class = "btn btn-primary pull-right" })
	</div>
</div>

<table class="table table-bordered table-striped table-condensed table-hover">
	<thead>
		<tr>
			<th></th>
			<th>
				<small>@Html.DisplayNameFor(model => model[0].Nombres)</small>
			</th>
			<th>
				<small>@Html.DisplayNameFor(model => model[0].Apellidos)</small>
			</th>
			<th>
				<small>@Html.DisplayNameFor(model => model[0].Edad)</small>
			</th>
			<th>
				<small>@Html.DisplayNameFor(model => model[0].IdGenero)</small>
			</th>
			<th>
				<small>@Html.DisplayNameFor(model => model[0].Curso)</small>
			</th>
			<th>
				<small>@Html.DisplayNameFor(model => model[0].Activo)</small>
			</th>
		</tr>
	</thead>
@foreach (var item in Model) {
	<tr>

		<td>
			<div class="btn-group">
				<a href="@Url.Action("Edit", new { Id = item.Id })" class="btn btn-mini btn-warning"><i class="icon-pencil"></i> Editar</a>
			</div>
		</td>
		<td>
			<small>@item.Nombres</small>
		</td>
		<td>
			<small>@item.Apellidos</small>
		</td>
		<td>
			<small>@(item.Edad)</small>
		</td>
		<td>
			<small>@(item.IdGenero == 1 ? "M" : "F")</small>
		</td>
		<td>
			<small>@(item.Curso)</small>
		</td>
		<td>
			<small>@(item.Activo == true ? "Activo" : "Inactivo")</small>
		</td>
	</tr>
}
</table>

Views/Estudiantes/_CreateOrEdit.cshtml
@using Entity.Models;
@model Estudiante

<div class="control-group">
	@Html.LabelFor(model => model.Identificacion, new { @class = "control-label" })
	<div class="controls">
		@Html.EditorFor(model => model.Identificacion)
		@Html.ValidationMessageFor(model => model.Identificacion)
	</div>
</div>
<div class="control-group">
	@Html.LabelFor(model => model.Nombres, new { @class = "control-label" })
	<div class="controls">
		@Html.EditorFor(model => model.Nombres)
		@Html.ValidationMessageFor(model => model.Nombres)
	</div>
</div>
<div class="control-group">
	@Html.LabelFor(model => model.Apellidos, new { @class = "control-label" })
	<div class="controls">
		@Html.EditorFor(model => model.Apellidos)
		@Html.ValidationMessageFor(model => model.Apellidos)
	</div>
</div>
<div class="control-group">
	@Html.LabelFor(model => model.Edad, new { @class = "control-label" })
	<div class="controls">
		@Html.EditorFor(model => model.Edad)
		@Html.ValidationMessageFor(model => model.Edad)
	</div>
</div>
<div class="control-group">
	@Html.LabelFor(model => model.IdGenero, new { @class = "control-label" })
	<div class="controls">
		<select asp-for="IdGenero" asp-items="@((IEnumerable<SelectListItem>)ViewBag.Generos)" class="">
		</select>
		@Html.ValidationMessageFor(model => model.IdGenero)
	</div>
</div>
<div class="control-group">
	@Html.LabelFor(model => model.Curso, new { @class = "control-label" })
	<div class="controls">
		@Html.EditorFor(model => model.Curso)
		@Html.ValidationMessageFor(model => model.Curso)
	</div>
</div>
<div class="control-group">
	@Html.LabelFor(model => model.Activo, new { @class = "control-label" })
	<div class="controls">
		<select asp-for="Activo">
			<option value="true" selected>Activo</option>
			<option value="false">Inactivo</option>
		</select>
		@Html.ValidationMessageFor(model => model.Activo)
	</div>
</div>

Views/IndraModel/Index.cshtml
@{
	ViewBag.Title = "Tables";
}

<ul class="breadcrumb">
	<li class="active">Tablas</li>
</ul>

<table class="table table-bordered table-striped">
	<thead>
		<tr>
			<th>Nombre de la tabla</th>
		</tr>
	</thead>

	<tr>
		<td>@Html.ActionLink("Calificaciones", "Index", "Calificaciones")</td>
	</tr>
	<tr>
		<td>@Html.ActionLink("Estudiantes", "Index", "Estudiantes")</td>
	</tr>
	<tr>
		<td>@Html.ActionLink("Asignaturas", "Index", "Asignaturas")</td>
	</tr>
</table>

Views/Shared/Titulo.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@*@ViewData["Title"]*@ - Indra.Web</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Indra.Web.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="IndraModel" asp-action="Index">Indra.Web</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Estudiantes" asp-action="Index">Estudiantes</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Asignaturas" asp-action="Index">Asignaturas</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Calificaciones" asp-action="Index">Calificaciones</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - Indra.Web - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>